### ISSUE TITLE
LLVM building

### ISSUE THREAD

**Issue by imenb** [avakar/cpp2sir#1]
Hi,

Could you please tell me more about LLVM making and building?
I'm not familiar with the C++ environment and I need some help if possible.

Thank you in advance.

**Comment by avakar** [comment]
Hi, just follow the instructions here: http://clang.llvm.org/get_started.html. Basically, all you have to do is checkout llvm and clang (the latter goes into llvm/tools directory), then you configure/make/make install (or use cmake). Make sure you use the correct versions of the two packages, otherwise cpp2sir may fail to compile.

**Comment by imenb** [comment]
thank you for your help.
Now when compiling cpp2sir I have the following error : cfg.hpp:87: error: `none_t' is not a member of`boost'

have you any idea about the error's cause ?

**Comment by avakar** [comment]
Hmm, that's strange. There's `#include <boost/none.hpp>` on line 7. What version of Boost do you have installed?

**Comment by imenb** [comment]
the Boost I'm using is 1_32.
One thing else ... I have deleted the option    "-fno-rtti"  from the flags.make file because I had the error :

"
/usr/include/boost/variant/variant.hpp: In member function `const std::type_info& boost::detail::variant::reflect::operator()(const T&) const':
/usr/include/boost/variant/variant.hpp:702: error: cannot use typeid with -fno-rtti
"

Could it be the cause ?? 
Should I use a newer version of boost ? 

Thanks for the help.

**Comment by avakar** [comment]
Yes, upgrade Boost. The current version is 1.48, 1.32 is quite old.

**Comment by avakar** [comment]
As for `-fno-rtti`, there should be no problem if you remove it, except the binary might get bigger. It should work with it though. Please try it with the new Boost and let me know.

**Comment by imenb** [comment]
Hi again,
here the results of my tests :
I'm using the boost 1.48. and I have two alternatives :
1/ If I keep the -fno-rtti option I have the following error :

---

from /udir/imenb/ALMAP/AnalyseurStatiqueDeCode/avakar-cpp2sir-8897646/cfg.cpp:1:
/udir/imenb/ALMAP/AnalyseurStatiqueDeCode/boost_1_48_0/boost/variant/variant.hpp: In member function `const std::type_info& boost::detail::variant::reflect::operator()(const T&) const':
/udir/imenb/ALMAP/AnalyseurStatiqueDeCode/boost_1_48_0/boost/variant/variant.hpp:749: error: cannot use typeid with -fno-rttiIn file included from /udir/imenb/ALMAP/AnalyseurStatiqueDeCode/avakar-cpp2sir-8897646/cfg.hpp:11,
                 from /udir/imenb/ALMAP/AnalyseurStatiqueDeCode/avakar-cpp2sir-8897646/cfg.cpp:1:
/udir/imenb/ALMAP/AnalyseurStatiqueDeCode/boost_1_48_0/boost/lexical_cast.hpp: In constructor`boost::bad_lexical_cast::bad_lexical_cast()':
/udir/imenb/ALMAP/AnalyseurStatiqueDeCode/boost_1_48_0/boost/lexical_cast.hpp:98: error: cannot use typeid with -fno-rtti
/udir/imenb/ALMAP/AnalyseurStatiqueDeCode/boost_1_48_0/boost/lexical_cast.hpp:98: error: cannot use typeid with -fno-rtti
/udir/imenb/ALMAP/AnalyseurStatiqueDeCode/boost_1_48_0/boost/lexical_cast.hpp: In static member function `static Target boost::detail::lexical_cast_do_cast<Target, Source>::lexical_cast_impl(const Source&)':
/udir/imenb/ALMAP/AnalyseurStatiqueDeCode/boost_1_48_0/boost/lexical_cast.hpp:1750: error: cannot use typeid with -fno-rtti
/udir/imenb/ALMAP/AnalyseurStatiqueDeCode/boost_1_48_0/boost/lexical_cast.hpp:1750: error: cannot use typeid with -fno-rtti
/udir/imenb/ALMAP/AnalyseurStatiqueDeCode/boost_1_48_0/boost/lexical_cast.hpp: In static member function`static Target boost::detail::lexical_cast_dynamic_num_not_ignoring_minus<Target, Source>::lexical_cast_impl(const Source&)':
/udir/imenb/ALMAP/AnalyseurStatiqueDeCode/boost_1_48_0/boost/lexical_cast.hpp:1810: error: cannot use typeid with -fno-rtti
/udir/imenb/ALMAP/AnalyseurStatiqueDeCode/boost_1_48_0/boost/lexical_cast.hpp:1810: error: cannot use typeid with -fno-rtti
/udir/imenb/ALMAP/AnalyseurStatiqueDeCode/boost_1_48_0/boost/lexical_cast.hpp: In static member function `static Target boost::detail::lexical_cast_dynamic_num_ignoring_minus<Target, Source>::lexical_cast_impl(const Source&)':
/udir/imenb/ALMAP/AnalyseurStatiqueDeCode/boost_1_48_0/boost/lexical_cast.hpp:1837: error: cannot use typeid with -fno-rtti
/udir/imenb/ALMAP/AnalyseurStatiqueDeCode/boost_1_48_0/boost/lexical_cast.hpp:1837: error: cannot use typeid with -fno-rtti

---

2/ if I remove the option. the compilation is OK but at the linking time I have the following error :

---

Linking CXX executable cpp2sir
CMakeFiles/cpp2sir.dir/main.cpp.o(.gnu.linkonce.r._ZTI15MyASTDumpAction+0x8): undefined reference to `typeinfo for clang::ASTFrontendAction'
CMakeFiles/cpp2sir.dir/main.cpp.o(.gnu.linkonce.r._ZTI10MyConsumer+0x8): undefined reference to`typeinfo for clang::ASTConsumer'
/udir/imenb/ALMAP/AnalyseurStatiqueDeCode/LLVM/buildclang/clang+llvm-2.9-i686-linux/lib/libclangFrontend.a(CompilerInvocation.o)(.text._ZNSs12_S_constructIPcEES0_T_S1_RKSaIcESt20forward_iterator_tag[char\* std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_construct<char*>(char_, char_, std::allocator<char> const&, std::forward_iterator_tag)]+0xb1): In function `char* std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_construct<char*>(char*, char*, std::allocator<char> const&, std::forward_iterator_tag)':
: undefined reference to`std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep::_M_set_length_and_sharable(unsigned int)'
/udir/imenb/ALMAP/AnalyseurStatiqueDeCode/LLVM/buildclang/clang+llvm-2.9-i686-linux/lib/libclangSerialization.a(ASTReader.o)(.text._ZNSs12_S_constructIPKyEEPcT_S3_RKSaIcESt20forward_iterator_tag[char\* std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_construct<unsigned long long const*>(unsigned long long const_, unsigned long long const_, std::allocator<char> const&, std::forward_iterator_tag)]+0xac): In function `char* std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_construct<unsigned long long const*>(unsigned long long const*, unsigned long long const*, std::allocator<char> const&, std::forward_iterator_tag)':
: undefined reference to`std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep::_M_set_length_and_sharable(unsigned int)'
/udir/imenb/ALMAP/AnalyseurStatiqueDeCode/LLVM/buildclang/clang+llvm-2.9-i686-linux/lib/libclangSerialization.a(ASTReader.o)(.text._ZNSs12_S_constructIPyEEPcT_S2_RKSaIcESt20forward_iterator_tag[char\* std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_construct<unsigned long long*>(unsigned long long_, unsigned long long_, std::allocator<char> const&, std::forward_iterator_tag)]+0xac): In function `char* std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_S_construct<unsigned long long*>(unsigned long long*, unsigned long long*, std::allocator<char> const&, std::forward_iterator_tag)':
: undefined reference to`std::basic_string<char, std::char_traits<char>, std::allocator<char> >::_Rep::_M_set_length_and_sharable(unsigned int)'
/udir/imenb/ALMAP/AnalyseurStatiqueDeCode/LLVM/buildclang/clang+llvm-2.9-i686-linux/lib/libLLVMSupport.a(Signals.o)(.text+0x600): In function `_ZL15PrintStackTracePv':
: undefined reference to`dladdr'
/udir/imenb/ALMAP/AnalyseurStatiqueDeCode/LLVM/buildclang/clang+llvm-2.9-i686-linux/lib/libLLVMSupport.a(Signals.o)(.text+0x690): In function `_ZL15PrintStackTracePv':
: undefined reference to`dladdr'
collect2: ld returned 1 exit status
make[2]: **\* [cpp2sir] Error 1
make[1]: **\* [CMakeFiles/cpp2sir.dir/all] Error 2

---

Could you please help :(
Thank you

**Comment by namankumar** [comment]
Were you able to figure out how to compile clang with rtti? I have the latest version of boost and llvm+clang but I'm getting the same errors.

@imenb, did it work for you?
